spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nasa
    username: postgres
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
nasa:
  url: https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity
  key: ${apikey}
